version: "3"
services:
  mt:
    build:
      context: ${DOCKER_MT_BUILD_CONTEXT:-mt}
      dockerfile: ${DOCKER_MT_DOCKERFILE}
      args:
        - DOCKER_NODEJS_IMAGE=${DOCKER_NODEJS_IMAGE:-node:16.13.2}
        - DOCKER_MT_IMAGE=${DOCKER_MT_IMAGE:-movabletype/test:perl-5.36}
    restart: always
    working_dir: /var/www/cgi-bin/mt
    entrypoint: /usr/local/bin/docker-entrypoint.sh
    environment:
      NLS_LANG: ${NLS_LANG:-Japanese_Japan.UTF8}
      MT_DEV_UPDATE_BRANCH: ${UPDATE_BRANCH:-yes}
      DOCKER_MT_SERVICES: ${DOCKER_MT_SERVICES}
      DOCKER_MT_CPANFILES: ${DOCKER_MT_CPANFILES}
      APACHE_LOG_DIR: ${APACHE_LOG_DIR:-/tmp/apache2/log}
      APACHE_PID_FILE: ${APACHE_PID_FILE:-/tmp/apache2/run/apache2.pid}
    volumes:
      - "..:/mt-dev"
      - "${MT_HOME_PATH:-../../movabletype}:/var/www/cgi-bin/mt:${DOCKER_VOLUME_MOUNT_FLAG:-rw}"
      - "${MT_CONFIG_CGI_SRC_PATH:-../mt-config.cgi-original}:${MT_CONFIG_CGI_DEST_PATH:-/var/www/cgi-bin/mt/mt-config.cgi}:${DOCKER_VOLUME_MOUNT_FLAG:-rw}"
      - "${BASE_SITE_PATH:-site}:/var/www/html:${DOCKER_VOLUME_MOUNT_FLAG:-rw}"
      - "support:/var/www/cgi-bin/mt/mt-static/support:${DOCKER_VOLUME_MOUNT_FLAG:-rw}"
      # override entrypoint
      - "./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
    labels:
      mt-dev.service: "mt"

  httpd:
    build:
      context: ${DOCKER_HTTPD_BUILD_CONTEXT:-httpd}
      dockerfile: ${DOCKER_HTTPD_DOCKERFILE}
      args:
        - DOCKER_HTTPD_IMAGE=${DOCKER_HTTPD_IMAGE:-movabletype/test:php-8.0}
    restart: always
    entrypoint: "/usr/local/bin/docker-entrypoint.sh"
    environment:
      NLS_LANG: ${NLS_LANG:-Japanese_Japan.UTF8}
      APACHE_LOG_DIR: ${APACHE_LOG_DIR:-/tmp/apache2/log}
      APACHE_PID_FILE: ${APACHE_PID_FILE:-/tmp/apache2/run/apache2.pid}
    volumes:
      - "..:/mt-dev"
      - "${MT_HOME_PATH:-../../movabletype}:/var/www/cgi-bin/mt:${DOCKER_VOLUME_MOUNT_FLAG:-rw}"
      - "${MT_CONFIG_CGI_SRC_PATH:-../mt-config.cgi-original}:${MT_CONFIG_CGI_DEST_PATH:-/var/www/cgi-bin/mt/mt-config.cgi}:${DOCKER_VOLUME_MOUNT_FLAG:-rw}"
      - "${BASE_SITE_PATH:-site}:/var/www/html:${DOCKER_VOLUME_MOUNT_FLAG:-rw}"
      - "support:/var/www/cgi-bin/mt/mt-static/support:${DOCKER_VOLUME_MOUNT_FLAG:-rw}"
      # override entrypoint
      - "./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      # proxy setting
      - "./cgi-bin-mt.htaccess:/var/www/html/cgi-bin/mt/.htaccess"
      - "./cgi-bin-mt.htaccess:/var/www/cgi-bin/mt/.htaccess"
    ports:
      - "${HTTPD_EXPOSE_PORT:-80}:80"
    command: apache2-foreground

  mt-watcher:
    build:
      context: mt-watcher
    working_dir: /var/www/cgi-bin/mt
    environment:
      PERL_FNS_NO_OPT: ${PERL_FNS_NO_OPT:-0}
      DISABLE_MT_WATCHER: ${DISABLE_MT_WATCHER:-0}
    volumes:
      - "${MT_HOME_PATH:-../../movabletype}:/var/www/cgi-bin/mt"
      - "./mt-watcher.pl:/usr/local/lib/mt/bin/mt-watcher.pl"
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  site:
    driver: local
  support:
    driver: local
  mt-dev-mt-home-tmp:
    external: true
