version: "3"
services:
  mt:
    image: ${DOCKER_MT_IMAGE:-movabletype/test:perl-5.28}
    restart: always
    working_dir: /var/www/cgi-bin/mt
    entrypoint: /usr/local/bin/docker-entrypoint.sh
    environment:
      NLS_LANG: ${NLS_LANG:-Japanese_Japan.UTF8}
      MT_DEV_UPDATE_BRANCH: ${UPDATE_BRANCH:-yes}
    volumes:
      - "..:/mt-dev"
      - "${MT_HOME_PATH:-../../movabletype}:/var/www/cgi-bin/mt:${DOCKER_VOLUME_MOUNT_FLAG}"
      - "${MT_CONFIG_CGI_SRC_PATH:-../mt-config.cgi-original}:${MT_CONFIG_CGI_DEST_PATH:-/var/www/cgi-bin/mt/mt-config.cgi}:${DOCKER_VOLUME_MOUNT_FLAG}"
      - "${BASE_SITE_PATH:-site}:/var/www/html:${DOCKER_VOLUME_MOUNT_FLAG}"
      - "support:/var/www/cgi-bin/mt/mt-static/support:${DOCKER_VOLUME_MOUNT_FLAG}"
      # override entrypoint
      - "./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"

  httpd:
    image: ${DOCKER_HTTPD_IMAGE:-movabletype/test:php-7.3}
    restart: always
    entrypoint: "/usr/local/bin/docker-entrypoint.sh"
    volumes:
      - "..:/mt-dev"
      - "${MT_HOME_PATH:-../../movabletype}:/var/www/cgi-bin/mt:${DOCKER_VOLUME_MOUNT_FLAG}"
      - "${MT_CONFIG_CGI_SRC_PATH:-../mt-config.cgi-original}:${MT_CONFIG_CGI_DEST_PATH:-/var/www/cgi-bin/mt/mt-config.cgi}:${DOCKER_VOLUME_MOUNT_FLAG}"
      - "${BASE_SITE_PATH:-site}:/var/www/html:${DOCKER_VOLUME_MOUNT_FLAG}"
      - "support:/var/www/cgi-bin/mt/mt-static/support:${DOCKER_VOLUME_MOUNT_FLAG}"
      # override entrypoint
      - "./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      # proxy setting
      - "./cgi-bin-mt.htaccess:/var/www/html/cgi-bin/mt/.htaccess"
      - "./cgi-bin-mt.htaccess:/var/www/cgi-bin/mt/.htaccess"
    ports:
      - "${HTTPD_EXPOSE_PORT:-80}:80"
    command: apache2-foreground

volumes:
  site:
    driver: local
  support:
    driver: local
  mt-dev-mt-home-tmp:
    external: true
