services:
  mailpit:
    image: ${DOCKER_MAILPIT_IMAGE:-axllent/mailpit}
    restart: always
    ports:
      - "${MAILPIT_EXPOSE_PORT:-8025}:8025"
    environment:
      - MP_DATABASE=/data/mailpit.db
    volumes:
      - mp_database:/data

volumes:
  mp_database:
    driver: local
