services:
  db:
    image: ${DOCKER_MYSQL_IMAGE:-mysql:8.0.32}
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: ${DOCKER_MYSQL_COMMAND}
    volumes:
      - "..:/mt-dev"
      - "./mysql/conf.d:/etc/mysql/conf.d"
      - "${DOCKER_MYSQL_VOLUME:-mysql8}:/var/lib/mysql"
volumes:
  mariadb10:
    driver: local
  mysql9:
    driver: local
  mysql8:
    driver: local
  mysql5:
    driver: local
