#!/bin/bash

exec starman \
    -Iextlib \
    -MCGI \
    -MFile::Spec \
    -MCGI::Cookie \
    -MLWP::UserAgent \
    -MHTML::Entities \
    -MScalar::Util \
    -MDBI \
    -MDBD::mysql \
    -MImage::Magick \
    -E production \
    --port=80 \
    --workers=2 \
    --pid=$MT_PID_FILE_PATH \
    "$@"
