#cloud-config

runcmd:
  - /bin/bash
  - -c
  - |
    #!/bin/bash
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y make git zip \
      docker.io \
      mysql-client
    # required by HTTP::Tiny
    apt-get install -y libio-socket-ssl-perl
    curl -L https://github.com/docker/compose/releases/download/1.26.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
    # for NFS
    apt-get install -y nfs-common
    adduser ubuntu docker
